name: Check notification

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
     - 'master'

jobs:
  notify:
    name: notify on change
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
